[tool.poetry]
name = "coco-docker"
version = "0.1.1"
description = "CoCo: Your Container Companion — A helpful CLI for Docker tasks"
authors = ["teismar <eismartim@gmail.com>"]
readme = "README.md"
packages = [
    { include = "coco" }
]

include = [
    "assets/logo.txt",
    "data/funfacts.txt"
]

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.9.4"
typer = "^0.15.1"
pyyaml = "^6.0.2"

[tool.poetry.scripts]
coco = "coco.coco:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
